# Generated by Django 2.1.5 on 2019-01-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workedYears', models.FloatField(null=True)),
                ('salaryBrutto', models.FloatField(null=True)),
            ],
        ),
    ]
