# Generated by Django 2.1.5 on 2019-01-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salaryBrutto',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='salary',
            name='workedYears',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
